### ISSUE TITLE
widget always loading

### ISSUE THREAD

**Issue by futantan** [okx/dex-widget#13]
![CleanShot 2024-11-15 at 18 06 22@2x](https://github.com/user-attachments/assets/ef33a430-7789-4211-b578-d7ac66c44bd5)

I tried the following:
- play with https://okx.github.io/dex-widget/ not working, it's always loading
- Clone this repo and run it on my local. still no luck

I noticed error `Uncaught ReferenceError: CandleChartV2 is not defined` from the console

**Comment by fwx5618177** [comment]
Thanks for your precise issue, I would contact with our colleagues.

**Comment by toringo** [comment]
Fixed the issue, you can update latest package.
